# Default values for linkerd2-trust-anchor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

"tls":
  "crt": |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  "key": |
    -----BEGIN EC PRIVATE KEY-----
    -----END EC PRIVATE KEY-----
