apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-ca
  namespace: cert-manager
spec:
  ca:
    secretName: linkerd-ca
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: linkerd-ca
  namespace: cert-manager
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}