apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  secretName: linkerd-identity-issuer
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth