apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "linkd2-trust-anchor.fullname" . }}
  labels:
    {{- include "linkd2-trust-anchor.labels" . | nindent 4 }}
spec:
  secretName: {{ include "linkd2-trust-anchor.fullname" . }}-issuer
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: {{ include "linkd2-trust-anchor.fullname" . }}
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth