apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkd2-trust-anchor.fullname" . }}
  labels:
    {{- include "linkd2-trust-anchor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "linkd2-trust-anchor.selectorLabels" . | nindent 4 }}
