apiVersion: v1
kind: Secret
metadata:
  name: linkerd-trust-anchor
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
{{- if $.Values.annotations }}
  annotations:
{{ toYaml $.Values.annotations | indent 4 }}
{{- end }}
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
type: kubernetes.io/tls
