apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: linkerd
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  ca:
    secretName: webhook-issuer-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: linkerd-viz
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  ca:
    secretName: webhook-issuer-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: linkerd-jaeger
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  ca:
    secretName: webhook-issuer-tls
