apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  secretName: linkerd-policy-validator-k8s-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-policy-validator.linkerd.svc
  dnsNames:
  - linkerd-policy-validator.linkerd.svc
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8    
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  secretName: linkerd-proxy-injector-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc
  dnsNames:
  - linkerd-proxy-injector.linkerd.svc
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc
  dnsNames:
  - linkerd-sp-validator.linkerd.svc
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap
  namespace: linkerd-viz
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  secretName: tap-k8s-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: tap.linkerd-viz.svc
  dnsNames:
  - tap.linkerd-viz.svc
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth  
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-tap-injector
  namespace: linkerd-viz
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  secretName: tap-injector-k8s-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: tap-injector.linkerd-viz.svc
  dnsNames:
  - tap-injector.linkerd-viz.svc
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth    
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-injector
  namespace: linkerd-jaeger
  labels:
    {{- include "linkerd2-trust-anchor.labels" . | nindent 4 }}
spec:
  secretName: jaeger-injector-k8s-tls
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: jaeger-injector.linkerd-jaeger.svc
  dnsNames:
  - jaeger-injector.linkerd-jaeger.svc
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth      